import { z } from 'zod';

/**
 * One entry in the runs manifest. Generated by `scripts/copy-data.mjs`
 * at predev/prebuild time so the UI can list available runs without
 * doing a directory listing at runtime.
 */
export const RunManifestEntrySchema = z.object({
  filename: z.string(),
  scenario: z.string(),
  timestamp: z.string(),
  claimsCount: z.number().int().nonnegative(),
  adr: z.string().optional(),
});
export type RunManifestEntry = z.infer<typeof RunManifestEntrySchema>;

export const RunManifestSchema = z.object({
  generatedAt: z.string(),
  sourceDir: z.string(),
  runs: z.array(RunManifestEntrySchema),
});
export type RunManifest = z.infer<typeof RunManifestSchema>;
